services:
  credits:
    build: 
      context: .
      dockerfile: ./apps/credits/Dockerfile
      target: development
    command: pnpm run start:dev credits
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    ports:
      - '27017:27017'